### ISSUE TITLE
Google Translate backend only translates to English

### ISSUE THREAD

**Issue by miguelangelnieto** [dialect-app/dialect#151]
When choosing Google Translate, it only translates to English. See the following screenshot:

![Screenshot from 2021-04-09 20-53-54](https://user-images.githubusercontent.com/810868/114227893-ea88f680-9975-11eb-907b-2ba5022b25e1.png)

Same happens if I choose Spanish to Russian.

I am using Dialect 1.2.0, Flatpak, on Fedora 34.

**Comment by LyesSaadi** [comment]
Happened to me sometimes, but I could not reproduce it consistently :/. Seems to be Google Translate-specific since it never happened to me with LibreTranslate... Maybe is it a temporary Google API ban? Or a googletrans error?

**Comment by fushinari** [comment]
Yeah, my guesses are the same as @LyesSaadi . Sadly nothing we can do about it for now I think.

**Comment by miguelangelnieto** [comment]
Hi, thank you! Is there anything I can do to help in the diagnosis? Any debug flag or anyway to trace the API?

**Comment by fushinari** [comment]
Sorry but the issue is not in Dialect's code, it's in code we depend on. So there's nothing any of us can do about it right now, i.e. while we still depend on said code. I'd still like info if possible though :)

Are you able to consistently reproduce this? If not, how often does it happen? Are you able to use Google Translate normally from your browser? Is the issue specific to some language pairs?

**Comment by miguelangelnieto** [comment]
Yes, I can reproduce it. It happens always, since the first moment after the installation. I choose to translate Spanish to any other language, and it always gets translated to English. Funny thing, if I click the button to get the audio, it uses the language accent. For example, if I translate "Hola" from Spanish to Russian, I will get "Hello", but the audio will be played with strong Russian accent.

In the browser it works without problems.

**Comment by LyesSaadi** [comment]
I misunderstood the issue, I read your issue too quickly, and I now see what you mean. I tried it myself afterward and can confirm it is consistent! I didn't have this issue before, and I don't know what created it exactly?

(I thought you were talking about another bug where after a time translation no longer works and repeatedly give the same answer even when we change the sentence.)

**Comment by LyesSaadi** [comment]
This is maybe a dialect issue? While dialect refuses to translate, here is what googletrans 3.1.0a0 (so using the legacy method and the one in the flatpak) outputs:

```
lyes in dialect on  main [?] 
➜ translate "Bonjour, mon ami !"
[fr] Bonjour, mon ami !
    ->
[en] Hello my friend !
[pron.] Hello my friend !

lyes in dialect on  main [?] 
➜ translate "Hello my friend !" -d fr
[en] Hello my friend !
    ->
[fr] Bonjour, mon ami !
[pron.] Bonjour, mon ami !
```

**Comment by LyesSaadi** [comment]
Please disregard my last message, it now works...? Yeah, this is still inconsistent!

**Comment by fushinari** [comment]
> but the audio will be played with strong Russian accent.

@miguelangelnieto This is a very good sign. It means the issue is not on our side because it means language selection on our end was appropriate. So it points to an API issue again.

> This is maybe a dialect issue?

@LyesSaadi It can't be. Unless something really really unexpected and weird is going on, Dialect will always pass the text to translate, source language and target language to the API and just present the returned results. So in cases like this, it's almost certainly an issue on the API side.

As you probably know from previous discussions, we're very aware of the fact that the unofficial API we use for Google Translate is very unreliable. We've considered forking it and spending time fixing it, but we're unsure of how to move forward with it, especially with how it's a legal gray area. This is something we're still looking into, so this situation might change in the future, but for now, we're stuck with this.

**Comment by fushinari** [comment]
> Please disregard my last message, it now works...? Yeah, this is still inconsistent!

Yes... I get how that feels... No worries :laughing: Would be great if we could identify the conditions for failure though

**Comment by sorin-davidoi** [comment]
Running with the `HTTPX_LOG_LEVEL=debug` environment variable when this happens shows that the Google Translate API returns `429 Too Many Requests`.

**Comment by rafaelmardojai** [comment]
We show any failure in the UI, but seems like py-googletrans doesn't raise any error in this scenario and just returns the input text.
