### ISSUE TITLE
Listen button is greyed out when translating from Chinese

### ISSUE THREAD

**Issue by ptrv** [dialect-app/dialect#197]
I'm using dialect 1.3.0 flatpak version from flathub on Fedora 34. When translating from simplified Chinese the listen button is greyed out. The backend is Google Tanslate.

![Screenshot from 2021-09-15 00-21-36](https://user-images.githubusercontent.com/49775/133341966-dc665fd1-c6c2-4c31-9551-470c2f5dcee3.png)

**Comment by rafaelmardojai** [comment]
Hmm, the issue could be caused because `py-googletrans` the library we use for Google Translate support defines Simplified Chinese with the code `zh-cn`, but `gTTS` the library for Google Text-to-Speech defines it as `zh-CN`.

We can easily workaround it when checking if the language has Text-to-Speech support.
