### ISSUE TITLE
Offline Translation

### ISSUE THREAD

**Issue by dnet890** [dialect-app/dialect#211]
Hi
I am just curious. is it possible for this app to have other feature for  conduct offline translation by downloading offline data beforehand?

**Comment by BirdInFire** [comment]
i think not : 

Methodology,
1 : Disable internet
2 : open it
3 : Try translation

Result, network error

**Comment by fushinari** [comment]
It's actually kind of possible already if you setup a local LibreTranslate instance. As you can probably guess though, making this easier to do isn't a priority at the moment.

**Comment by BirdInFire** [comment]
> It's actually kind of possible already if you setup a local LibreTranslate instance. As you can probably guess though, making this easier to do isn't a priority at the moment.

Yep only responded to a question with the way to test him/herself.

**Comment by fushinari** [comment]
> Yep only responded to a question with the way to test him/herself.

This issue is a feature request, meaning he is already aware it's not present (at least in a more accessible manner) in the application.

**Comment by dtantono** [comment]
Well, like Google Translate/Microsoft Translator (Windows/Android/iOS) we can download offline data and perform a translation without an internet.

**Comment by BirdInFire** [comment]
> > Yep only responded to a question with the way to test him/herself.
> 
> This issue is a feature request, meaning he is already aware it's not present (at least in a more accessible manner) in the application.

an easy way (because you are a gnome app witch isn't the same userbase at them) check how https://github.com/argosopentech/argos-translate do it.

Their interface is more kde friendly and your Gnome friendly, some code exchange (to not recreate the wheel) can be done between these two app ?

I'm saying that with in mind i will help them to create flatpak (if i success).

**Comment by rafaelmardojai** [comment]
Argos is what powers Libre Translate. 

We have avoided offline translation for now because we need to implement a system to manage models. Also the translation quality of Argos hasn't motivated us to implement all that. There are good quality neural translation system like EasyNMT, but the models are very heavy, and that's a problem for regular users.

So that's the state of offline translation, we want it, but we lack the time and the current technologies have some issues to speed that up.

**Comment by jeblad** [comment]
Some of the [Apertium](https://apertium.org/) translation pairs are pretty lightweight, and could be an option. Apertium is a rule-based shallow translation engine, and best suited for close languages. In those specific cases it produce very good quality translations. An example is the translation between Norwegian Bokmål and Norwegian Nynorsk, which is excellent.

**Comment by happychameleon** [comment]
Perhaps it could be possible to use the work done by the [Bergamot](https://browser.mt/) project.
Mozilla created a plugin that lets you translate webpages offline, it was recently featured on their [hacks blog](https://hacks.mozilla.org/2022/06/neural-machine-translation-engine-for-firefox-translations-add-on/).

**Comment by rafaelmardojai** [comment]
@happychameleon see #183.

**Comment by jeblad** [comment]
There will be more and more focus on local processing of data as it has been shown again and again that cloud based services leaks data. I has worked at sites that has heightened security, and using software that leaks data to external sites all the time seems a bit weird.

I would really like an option where you could chose to use a local service, perhaps after being redirected to a page where the methods for enabling said service was described.

**Comment by mufeedali** [comment]
Better off tracked in individual issues like #183
